name: Deploy to Render

on:
  push:
    branches:
      - main  # ou la branche que tu veux

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d27qv9uuk2gs73eibqdg?key=jjyXAUbx6P4


